### PR TITLE
Updated project.json for netstandard16

### PR DESCRIPTION
**Pull request by cemremengu**

### CODE REVIEW

**Comment by jvandertil** [comment]
StructureMap 4.3.0 has just been released with .NET Standard 1.3/1.5 support, maybe include this in the pull request?

**Comment by jvandertil** [comment]
Also, I believe that Nancy.Bootstrappers.StructureMap/src/Nancy.Bootstrappers.StructureMap.MSBuild/Nancy.Bootstrappers.StructureMap.csproj has to be updated to use the new StructureMap version as well.

**Comment by jchannon** [comment]
Agreed

**Comment by cemremengu** [comment]
@jvandertil @jchannon

**Comment by jvandertil** [comment]
Great work! 

One more point: don't forget to update the csproj in MSBuild (https://github.com/NancyFx/Nancy.Bootstrappers.StructureMap/blob/master/src/Nancy.Bootstrappers.StructureMap.MSBuild/Nancy.Bootstrappers.StructureMap.csproj#L37 for example). Else the solution will not build if people use it (although it is probably deprecated? @khellang / @jchannon ?)

I'm not sure if the nuspec is still used, but that should probably refer to the latest SM version as well: https://github.com/NancyFx/Nancy.Bootstrappers.StructureMap/blob/master/src/Nancy.Bootstrappers.StructureMap/Nancy.Bootstrappers.StructureMap.nuspec (@jchannon ?)

I'd really like to see this merged though :) :shipit:

**Comment by cemremengu** [comment]
Thanks @jvandertil  I missed those sorry. Working on them right now, not sure but I think `msbuild` is deprecated though.

**Comment by jvandertil** [comment]
No worries, I've missed them a couple of times as well so that's how I know ;).

I'd reckon they are deprecated as well, but as long as they are not removed it's probably best to maintain them I guess.

**Comment by cemremengu** [comment]
I have updated the `nuspec`. I checked MSBuild stuff but they seem _very_ detached from the main project so it seems that there is no easy way (at least for me :)) to update them safely.

I will wait until @thecodejunkie @khellang @jchannon say something about them. :)

**Comment by jchannon** [comment]
If you open Nancy.Bootstrappers.StructureMap.sln you should be able to do
it.

**Comment by jchannon** [comment]
TBH we can probably ignore the nuspec files as they are no longer used

**Comment by cemremengu** [comment]
Ah ok so the old solution is the one for those @jchannon

**Comment by jchannon** [comment]
Reminds me, we need to get all the other projects setup on AppVeyor

**Comment by cemremengu** [comment]
Nuspecs are actually create arrogance when they are not updated. @jchannon 

Something like "Version Y is expected but Version X was specified"

**Comment by cemremengu** [comment]
What's up with this one ?

**Pull request merged**
