### PR TITLE
Directly instantiate IRequestStartup types

### PR DESCRIPTION
**Pull request by jvandertil**
There is no need to register the IRequestStartup types in the container.
Since the known concrete types are passed into the function, we can
ask StructureMap to directly instantiate them. This avoids a Configure
step each time a request is done to a Nancy module.

This is what I suggested in issue #27.

### CODE REVIEW

**Comment by gregsochanik** [comment]
Great, that does look a much better solution, I just wanted to revert to a known working state and add that test.

The test with the ViewBag parameter switch is much more elegant than the one I added :+1:. You can remove the `using global::StructureMap` that I added to `StructureMapNancyBootstrapperFixture`

Although - the original code specified a difference between `Lifetime.PerRequest` and `Lifetime.Singleton` based on the `container.Type`. 

Does anyone know the reason for this, or whether it's relevant? Are `IRequestStartup`s already specified as `LifeTime.PerRequest` anywhere else. This was the bit I was unsure about.

**Comment by jvandertil** [comment]
Well the request container is always a nested container, so that statement will always evaluate to true. (See: https://github.com/NancyFx/Nancy.Bootstrappers.StructureMap/blob/master/src/Nancy.Bootstrappers.StructureMap/StructureMapNancyBootstrapper.cs#L171).

I'll take a look at cleaning up the code some more :).

**Comment by jvandertil** [comment]
Also fixed the Visual Studio warning about mixed line endings

**Comment by khellang** [comment]
Is this PR ready to go? I *really* think we need to nag @NancyFx/owners a bit more about giving other peeps push access to the different bootstrapper repos :smile:

**Comment by asbjornu** [comment]
@khellang, I think it looks good and @gregsochanik agrees, so let's fold it in! I completely agree that NancyFX/Nancy#1712 needs to be resolved. :wink:

**Pull request merged**
